import pandas as pd

# Load the dataset (assuming it's in a list of dictionaries for simplicity)
data = [
    {"username": "donna16", "total_attempts": 22, "failures": 7, "failure_rate": 0.318, "unique_ips": 1, "odd_hours": 2},
    {"username": "kdelgado", "total_attempts": 26, "failures": 8, "failure_rate": 0.308, "unique_ips": 1, "odd_hours": 5},
    {"username": "jamie59", "total_attempts": 20, "failures": 6, "failure_rate": 0.300, "unique_ips": 1, "odd_hours": 9},
    {"username": "timothy59", "total_attempts": 20, "failures": 6, "failure_rate": 0.300, "unique_ips": 1, "odd_hours": 1},
    {"username": "lisa72", "total_attempts": 22, "failures": 6, "failure_rate": 0.273, "unique_ips": 1, "odd_hours": 3},
    {"username": "vazquezjudith", "total_attempts": 23, "failures": 6, "failure_rate": 0.261, "unique_ips": 1, "odd_hours": 7},
    {"username": "donald19", "total_attempts": 23, "failures": 6, "failure_rate": 0.261, "unique_ips": 3, "odd_hours": 9},
    {"username": "jmahoney", "total_attempts": 23, "failures": 6, "failure_rate": 0.261, "unique_ips": 1, "odd_hours": 2},
    {"username": "johnbenton", "total_attempts": 23, "failures": 6, "failure_rate": 0.261, "unique_ips": 1, "odd_hours": 2},
    {"username": "brianfrost", "total_attempts": 27, "failures": 7, "failure_rate": 0.259, "unique_ips": 1, "odd_hours": 8},
    {"username": "brandonduncan", "total_attempts": 24, "failures": 6, "failure_rate": 0.250, "unique_ips": 1, "odd_hours": 13},
    {"username": "peter87", "total_attempts": 24, "failures": 6, "failure_rate": 0.250, "unique_ips": 1, "odd_hours": 3},
    {"username": "gprice", "total_attempts": 24, "failures": 6, "failure_rate": 0.250, "unique_ips": 2, "odd_hours": 4},
    {"username": "jhall", "total_attempts": 21, "failures": 5, "failure_rate": 0.238, "unique_ips": 1, "odd_hours": 2},
    {"username": "daniellestokes", "total_attempts": 21, "failures": 5, "failure_rate": 0.238, "unique_ips": 1, "odd_hours": 7},
    {"username": "kimberlyrodriguez", "total_attempts": 21, "failures": 5, "failure_rate": 0.238, "unique_ips": 1, "odd_hours": 3},
    {"username": "william98", "total_attempts": 21, "failures": 5, "failure_rate": 0.238, "unique_ips": 1, "odd_hours": 4},
    {"username": "matthew58", "total_attempts": 22, "failures": 5, "failure_rate": 0.227, "unique_ips": 1, "odd_hours": 9},
    {"username": "norrisjustin", "total_attempts": 22, "failures": 5, "failure_rate": 0.227, "unique_ips": 1, "odd_hours": 6},
    {"username": "douglascurtis", "total_attempts": 23, "failures": 5, "failure_rate": 0.217, "unique_ips": 1, "odd_hours": 1},
    {"username": "summer44", "total_attempts": 23, "failures": 5, "failure_rate": 0.217, "unique_ips": 2, "odd_hours": 3},
    {"username": "panderson", "total_attempts": 23, "failures": 5, "failure_rate": 0.217, "unique_ips": 1, "odd_hours": 1},
    {"username": "jessica17", "total_attempts": 23, "failures": 5, "failure_rate": 0.217, "unique_ips": 1, "odd_hours": 8},
    {"username": "christopher33", "total_attempts": 19, "failures": 4, "failure_rate": 0.211, "unique_ips": 1, "odd_hours": 7},
    {"username": "hquinn", "total_attempts": 19, "failures": 4, "failure_rate": 0.211, "unique_ips": 1, "odd_hours": 2},
    {"username": "rhill", "total_attempts": 24, "failures": 5, "failure_rate": 0.208, "unique_ips": 1, "odd_hours": 7},
    {"username": "alexanderstanley", "total_attempts": 24, "failures": 5, "failure_rate": 0.208, "unique_ips": 1, "odd_hours": 4},
    {"username": "rsims", "total_attempts": 24, "failures": 5, "failure_rate": 0.208, "unique_ips": 1, "odd_hours": 3},
    {"username": "douglasthompson", "total_attempts": 24, "failures": 5, "failure_rate": 0.208, "unique_ips": 1, "odd_hours": 4},
    {"username": "gregory00", "total_attempts": 24, "failures": 5, "failure_rate": 0.208, "unique_ips": 1, "odd_hours": 7},
    {"username": "travis79", "total_attempts": 24, "failures": 5, "failure_rate": 0.208, "unique_ips": 1, "odd_hours": 4},
    {"username": "keith15", "total_attempts": 20, "failures": 4, "failure_rate": 0.200, "unique_ips": 1, "odd_hours": 4},
    {"username": "freemansteve", "total_attempts": 20, "failures": 4, "failure_rate": 0.200, "unique_ips": 1, "odd_hours": 6},
    {"username": "anna88", "total_attempts": 21, "failures": 4, "failure_rate": 0.190, "unique_ips": 1, "odd_hours": 3},
    {"username": "ashleydavis", "total_attempts": 21, "failures": 4, "failure_rate": 0.190, "unique_ips": 1, "odd_hours": 6},
    {"username": "rodriguezjonathon", "total_attempts": 21, "failures": 4, "failure_rate": 0.190, "unique_ips": 1, "odd_hours": 8},
    {"username": "dbryant", "total_attempts": 21, "failures": 4, "failure_rate": 0.190, "unique_ips": 1, "odd_hours": 8},
    {"username": "jessicaballard", "total_attempts": 22, "failures": 4, "failure_rate": 0.182, "unique_ips": 1, "odd_hours": 6},
    {"username": "stacyhenderson", "total_attempts": 22, "failures": 4, "failure_rate": 0.182, "unique_ips": 1, "odd_hours": 2},
    {"username": "haleybaker", "total_attempts": 22, "failures": 4, "failure_rate": 0.182, "unique_ips": 1, "odd_hours": 5},
    {"username": "torresmichelle", "total_attempts": 22, "failures": 4, "failure_rate": 0.182, "unique_ips": 1, "odd_hours": 8},
    {"username": "gshaw", "total_attempts": 22, "failures": 4, "failure_rate": 0.182, "unique_ips": 1, "odd_hours": 2},
    {"username": "johngutierrez", "total_attempts": 23, "failures": 4, "failure_rate": 0.174, "unique_ips": 1, "odd_hours": 3},
    {"username": "vallen", "total_attempts": 23, "failures": 4, "failure_rate": 0.174, "unique_ips": 1, "odd_hours": 3},
    {"username": "lsims", "total_attempts": 23, "failures": 4, "failure_rate": 0.174, "unique_ips": 1, "odd_hours": 5},
    {"username": "stephaniedennis", "total_attempts": 23, "failures": 4, "failure_rate": 0.174, "unique_ips": 1, "odd_hours": 6},
    {"username": "mbutler", "total_attempts": 18, "failures": 3, "failure_rate": 0.167, "unique_ips": 1, "odd_hours": 4},
    {"username": "timothy68", "total_attempts": 19, "failures": 3, "failure_rate": 0.158, "unique_ips": 1, "odd_hours": 7},
    {"username": "frankscott", "total_attempts": 19, "failures": 3, "failure_rate": 0.158, "unique_ips": 1, "odd_hours": 5},
    {"username": "leahryan", "total_attempts": 19, "failures": 3, "failure_rate": 0.158, "unique_ips": 1, "odd_hours": 3},
    {"username": "owillis", "total_attempts": 19, "failures": 3, "failure_rate": 0.158, "unique_ips": 1, "odd_hours": 5},
    {"username": "kaylee95", "total_attempts": 20, "failures": 3, "failure_rate": 0.150, "unique_ips": 1, "odd_hours": 6},
    {"username": "parkercasey", "total_attempts": 20, "failures": 3, "failure_rate": 0.150, "unique_ips": 1, "odd_hours": 2},
    {"username": "terrence47", "total_attempts": 20, "failures": 3, "failure_rate": 0.150, "unique_ips": 1, "odd_hours": 3},
    {"username": "drichardson", "total_attempts": 20, "failures": 3, "failure_rate": 0.150, "unique_ips": 1, "odd_hours": 6},
    {"username": "cheryl12", "total_attempts": 20, "failures": 3, "failure_rate": 0.150, "unique_ips": 1, "odd_hours": 6},
    {"username": "conleyjames", "total_attempts": 20, "failures": 3, "failure_rate": 0.150, "unique_ips": 1, "odd_hours": 3},
    {"username": "robert38", "total_attempts": 20, "failures": 3, "failure_rate": 0.150, "unique_ips": 1, "odd_hours": 4},
    {"username": "ylopez", "total_attempts": 21, "failures": 3, "failure_rate": 0.143, "unique_ips": 1, "odd_hours": 2},
    {"username": "elizabeththompson", "total_attempts": 21, "failures": 3, "failure_rate": 0.143, "unique_ips": 1, "odd_hours": 2},
    {"username": "john63", "total_attempts": 21, "failures": 3, "failure_rate": 0.143, "unique_ips": 1, "odd_hours": 5},
    {"username": "logankline", "total_attempts": 21, "failures": 3, "failure_rate": 0.143, "unique_ips": 1, "odd_hours": 0},
    {"username": "lorilong", "total_attempts": 21, "failures": 3, "failure_rate": 0.143, "unique_ips": 1, "odd_hours": 3},
    {"username": "melaniehernandez", "total_attempts": 21, "failures": 3, "failure_rate": 0.143, "unique_ips": 2, "odd_hours": 4},
    {"username": "fernandezcourtney", "total_attempts": 21, "failures": 3, "failure_rate": 0.143, "unique_ips": 1, "odd_hours": 8},
    {"username": "jeffrey82", "total_attempts": 21, "failures": 3, "failure_rate": 0.143, "unique_ips": 2, "odd_hours": 3},
    {"username": "david67", "total_attempts": 22, "failures": 3, "failure_rate": 0.136, "unique_ips": 1, "odd_hours": 2},
    {"username": "halljessica", "total_attempts": 22, "failures": 3, "failure_rate": 0.136, "unique_ips": 1, "odd_hours": 5},
    {"username": "laurakaufman", "total_attempts": 22, "failures": 3, "failure_rate": 0.136, "unique_ips": 1, "odd_hours": 1},
    {"username": "francisco90", "total_attempts": 22, "failures": 3, "failure_rate": 0.136, "unique_ips": 2, "odd_hours": 6},
    {"username": "scottjohnson", "total_attempts": 22, "failures": 3, "failure_rate": 0.136, "unique_ips": 1, "odd_hours": 8},
    {"username": "wilsonlisa", "total_attempts": 22, "failures": 3, "failure_rate": 0.136, "unique_ips": 1, "odd_hours": 7},
    {"username": "debracollier", "total_attempts": 22, "failures": 3, "failure_rate": 0.136, "unique_ips": 3, "odd_hours": 8},
    {"username": "hollandwendy", "total_attempts": 23, "failures": 3, "failure_rate": 0.130, "unique_ips": 1, "odd_hours": 4},
    {"username": "kempjoel", "total_attempts": 23, "failures": 3, "failure_rate": 0.130, "unique_ips": 1, "odd_hours": 5},
    {"username": "meganrose", "total_attempts": 23, "failures": 3, "failure_rate": 0.130, "unique_ips": 1, "odd_hours": 6},
    {"username": "yvega", "total_attempts": 23, "failures": 3, "failure_rate": 0.130, "unique_ips": 2, "odd_hours": 2},
    {"username": "johngarrison", "total_attempts": 23, "failures": 3, "failure_rate": 0.130, "unique_ips": 1, "odd_hours": 5},
    {"username": "steven00", "total_attempts": 23, "failures": 3, "failure_rate": 0.130, "unique_ips": 1, "odd_hours": 3},
    {"username": "kathleenbowman", "total_attempts": 17, "failures": 2, "failure_rate": 0.118, "unique_ips": 1, "odd_hours": 1},
    {"username": "rodneyjohnson", "total_attempts": 17, "failures": 2, "failure_rate": 0.118, "unique_ips": 3, "odd_hours": 6},
    {"username": "kylieabbott", "total_attempts": 18, "failures": 2, "failure_rate": 0.111, "unique_ips": 1, "odd_hours": 4},
    {"username": "foleyjose", "total_attempts": 18, "failures": 2, "failure_rate": 0.111, "unique_ips": 1, "odd_hours": 3},
    {"username": "jamiehunter", "total_attempts": 18, "failures": 2, "failure_rate": 0.111, "unique_ips": 1, "odd_hours": 5},
    {"username": "tarahunt", "total_attempts": 18, "failures": 2, "failure_rate": 0.111, "unique_ips": 1, "odd_hours": 6},
    {"username": "josephjohnson", "total_attempts": 18, "failures": 2, "failure_rate": 0.111, "unique_ips": 1, "odd_hours": 3},
    {"username": "werneranna", "total_attempts": 19, "failures": 2, "failure_rate": 0.105, "unique_ips": 3, "odd_hours": 0},
    {"username": "griffinashley", "total_attempts": 19, "failures": 2, "failure_rate": 0.105, "unique_ips": 1, "odd_hours": 5},
    {"username": "denisebaker", "total_attempts": 19, "failures": 2, "failure_rate": 0.105, "unique_ips": 1, "odd_hours": 5},
    {"username": "gary33", "total_attempts": 19, "failures": 2, "failure_rate": 0.105, "unique_ips": 1, "odd_hours": 1},
    {"username": "joycekim", "total_attempts": 19, "failures": 2, "failure_rate": 0.105, "unique_ips": 1, "odd_hours": 0},
    {"username": "marissa71", "total_attempts": 19, "failures": 2, "failure_rate": 0.105, "unique_ips": 1, "odd_hours": 5},
    {"username": "stephanie56", "total_attempts": 19, "failures": 2, "failure_rate": 0.105, "unique_ips": 1, "odd_hours": 7},
    {"username": "ywilliams", "total_attempts": 19, "failures": 2, "failure_rate": 0.105, "unique_ips": 1, "odd_hours": 2},
    {"username": "joseph60", "total_attempts": 20, "failures": 2, "failure_rate": 0.100, "unique_ips": 2, "odd_hours": 1},
    {"username": "oboyd", "total_attempts": 20, "failures": 2, "failure_rate": 0.100, "unique_ips": 1, "odd_hours": 3},
    {"username": "courtneyanderson", "total_attempts": 20, "failures": 2, "failure_rate": 0.100, "unique_ips": 1, "odd_hours": 3},
    {"username": "ggreene", "total_attempts": 20, "failures": 2, "failure_rate": 0.100, "unique_ips": 1, "odd_hours": 3},
    {"username": "kevin90", "total_attempts": 20, "failures": 2, "failure_rate": 0.100, "unique_ips": 1, "odd_hours": 4},
    {"username": "houstoncody", "total_attempts": 20, "failures": 2, "failure_rate": 0.100, "unique_ips": 1, "odd_hours": 5},
    {"username": "sharonmullen", "total_attempts": 20, "failures": 2, "failure_rate": 0.100, "unique_ips": 1, "odd_hours": 3},
    {"username": "tuckerpaula", "total_attempts": 20, "failures": 2, "failure_rate": 0.100, "unique_ips": 1, "odd_hours": 6},
    {"username": "michelle42", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 8},
    {"username": "richardjuarez", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 4},
    {"username": "fredberry", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 5},
    {"username": "michael93", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 4},
    {"username": "miguel80", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 5},
    {"username": "ykaufman", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 5},
    {"username": "cervantesmichael", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 3, "odd_hours": 4},
    {"username": "nmorgan", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 1},
    {"username": "wyattmarcus", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 2, "odd_hours": 2},
    {"username": "elizabeth26", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 3},
    {"username": "dkent", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 2, "odd_hours": 5},
    {"username": "hbrown", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 3},
    {"username": "bradleycarmen", "total_attempts": 21, "failures": 2, "failure_rate": 0.095, "unique_ips": 1, "odd_hours": 6},
    {"username": "debbie57", "total_attempts": 22, "failures": 2, "failure_rate": 0.091, "unique_ips": 1, "odd_hours": 3},
    {"username": "barbara56", "total_attempts": 22, "failures": 2, "failure_rate": 0.091, "unique_ips": 2, "odd_hours": 6},
    {"username": "lori76", "total_attempts": 22, "failures": 2, "failure_rate": 0.091, "unique_ips": 1, "odd_hours": 3},
    {"username": "kevinrose", "total_attempts": 22, "failures": 2, "failure_rate": 0.091, "unique_ips": 1, "odd_hours": 3},
    {"username": "qkent", "total_attempts": 22, "failures": 2, "failure_rate": 0.091, "unique_ips": 1, "odd_hours": 4},
    {"username": "amy40", "total_attempts": 22, "failures": 2, "failure_rate": 0.091, "unique_ips": 2, "odd_hours": 4},
    {"username": "qwinters", "total_attempts": 15, "failures": 1, "failure_rate": 0.067, "unique_ips": 1, "odd_hours": 3},
    {"username": "lindaandrade", "total_attempts": 15, "failures": 1, "failure_rate": 0.067, "unique_ips": 2, "odd_hours": 7},
    {"username": "ysuarez", "total_attempts": 16, "failures": 1, "failure_rate": 0.062, "unique_ips": 1, "odd_hours": 4},
    {"username": "william33", "total_attempts": 17, "failures": 1, "failure_rate": 0.059, "unique_ips": 1, "odd_hours": 4},
    {"username": "kiaramorris", "total_attempts": 17, "failures": 1, "failure_rate": 0.059, "unique_ips": 2, "odd_hours": 3},
    {"username": "jessicapowell", "total_attempts": 18, "failures": 1, "failure_rate": 0.056, "unique_ips": 1, "odd_hours": 5},
    {"username": "gdixon", "total_attempts": 18, "failures": 1, "failure_rate": 0.056, "unique_ips": 1, "odd_hours": 3},
    {"username": "judy39", "total_attempts": 18, "failures": 1, "failure_rate": 0.056, "unique_ips": 1, "odd_hours": 3},
    {"username": "duane91", "total_attempts": 18, "failures": 1, "failure_rate": 0.056, "unique_ips": 1, "odd_hours": 4},
    {"username": "katie67", "total_attempts": 18, "failures": 1, "failure_rate": 0.056, "unique_ips": 1, "odd_hours": 2},
    {"username": "fjames", "total_attempts": 18, "failures": 1, "failure_rate": 0.056, "unique_ips": 1, "odd_hours": 1},
    {"username": "shawnmatthews", "total_attempts": 18, "failures": 1, "failure_rate": 0.056, "unique_ips": 1, "odd_hours": 5},
    {"username": "garypeterson", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 1, "odd_hours": 2},
    {"username": "snydertara", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 1, "odd_hours": 3},
    {"username": "kristykent", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 3, "odd_hours": 6},
    {"username": "larsenvictoria", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 1, "odd_hours": 3},
    {"username": "alexander06", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 1, "odd_hours": 7},
    {"username": "kathleenbarnett", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 1, "odd_hours": 5},
    {"username": "fmiller", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 2, "odd_hours": 5},
    {"username": "jacksonmichael", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 1, "odd_hours": 5},
    {"username": "peter57", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 1, "odd_hours": 1},
    {"username": "ijones", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 1, "odd_hours": 4},
    {"username": "wellsfrederick", "total_attempts": 19, "failures": 1, "failure_rate": 0.053, "unique_ips": 2, "odd_hours": 3},
    {"username": "gcampbell", "total_attempts": 20, "failures": 1, "failure_rate": 0.050, "unique_ips": 1, "odd_hours": 5},
    {"username": "gambleangela", "total_attempts": 20, "failures": 1, "failure_rate": 0.050, "unique_ips": 2, "odd_hours": 1},
    {"username": "lhogan", "total_attempts": 20, "failures": 1, "failure_rate": 0.050, "unique_ips": 1, "odd_hours": 4},
    {"username": "tracyclark", "total_attempts": 20, "failures": 1, "failure_rate": 0.050, "unique_ips": 1, "odd_hours": 1},
    {"username": "angelabarry", "total_attempts": 20, "failures": 1, "failure_rate": 0.050, "unique_ips": 1, "odd_hours": 4},
    {"username": "reneebarrett", "total_attempts": 20, "failures": 1, "failure_rate": 0.050, "unique_ips": 1, "odd_hours": 6},
    {"username": "shelly82", "total_attempts": 20, "failures": 1, "failure_rate": 0.050, "unique_ips": 1, "odd_hours": 5},
    {"username": "jonesshawn", "total_attempts": 21, "failures": 1, "failure_rate": 0.048, "unique_ips": 3, "odd_hours": 6},
    {"username": "uknight", "total_attempts": 21, "failures": 1, "failure_rate": 0.048, "unique_ips": 1, "odd_hours": 3},
    {"username": "lori84", "total_attempts": 21, "failures": 1, "failure_rate": 0.048, "unique_ips": 1, "odd_hours": 2},
    {"username": "kathleengibson", "total_attempts": 21, "failures": 1, "failure_rate": 0.048, "unique_ips": 1, "odd_hours": 6},
    {"username": "benjamin02", "total_attempts": 18, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 5},
    {"username": "robertssteven", "total_attempts": 19, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 6},
    {"username": "sreyes", "total_attempts": 18, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 3},
    {"username": "hkelly", "total_attempts": 18, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 6},
    {"username": "clewis", "total_attempts": 17, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 1},
    {"username": "gwendolyn93", "total_attempts": 19, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 4},
    {"username": "smithalicia", "total_attempts": 17, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 2},
    {"username": "moodylisa", "total_attempts": 17, "failures": 0, "failure_rate": 0.000, "unique_ips": 2, "odd_hours": 4},
    {"username": "lewislauren", "total_attempts": 20, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 7},
    {"username": "alfredsimon", "total_attempts": 17, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 2},
    {"username": "wsanchez", "total_attempts": 17, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 4},
    {"username": "smithphillip", "total_attempts": 19, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 7},
    {"username": "michaellopez", "total_attempts": 20, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 4},
    {"username": "lopezpatrick", "total_attempts": 18, "failures": 0, "failure_rate": 0.000, "unique_ips": 2, "odd_hours": 6},
    {"username": "nelsoncaitlyn", "total_attempts": 19, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 4},
    {"username": "millercraig", "total_attempts": 18, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 5},
    {"username": "cynthia13", "total_attempts": 14, "failures": 0, "failure_rate": 0.000, "unique_ips": 1, "odd_hours": 1}
]

# Convert to DataFrame
df = pd.DataFrame(data)

# Normalize the metrics (scale to 0-1)
def normalize(column):
    return (column - column.min()) / (column.max() - column.min()) if column.max() != column.min() else column * 0

df['norm_failure_rate'] = normalize(df['failure_rate'])
df['norm_unique_ips'] = normalize(df['unique_ips'])
df['norm_odd_hours'] = normalize(df['odd_hours'])

# Define weights
weights = {
    'failure_rate': 0.4,
    'unique_ips': 0.3,
    'odd_hours': 0.3
}

# Calculate anomaly score
df['anomaly_score'] = (
    weights['failure_rate'] * df['norm_failure_rate'] +
    weights['unique_ips'] * df['norm_unique_ips'] +
    weights['odd_hours'] * df['norm_odd_hours']
)

# Find the user with the highest anomaly score
most_anomalous_user = df.loc[df['anomaly_score'].idxmax()]

# Print the result
print("Most likely compromised user:")
print(f"Username: {most_anomalous_user['username']}")
print(f"Anomaly Score: {most_anomalous_user['anomaly_score']:.4f}")
print(f"Failure Rate: {most_anomalous_user['failure_rate']:.3f}")
print(f"Unique IPs: {most_anomalous_user['unique_ips']}")
print(f"Odd Hours: {most_anomalous_user['odd_hours']}")